- name: get keystore list
  shell: "{{ es_install_dir }}/bin/elasticsearch-keystore list"
  become_user: "{{ es_run_user }}"
  register: keystore_list
  changed_when: false

- name: add keystore
  shell: "echo '{{ item.value }}' | {{ es_install_dir }}/bin/elasticsearch-keystore add --stdin {{ item.key }}"
  become_user: "{{ es_run_user }}"
  when: 
    - item.key not in keystore_list.stdout
    - item.state is not defined or item.state == 'present'
  loop: "{{ es_keystores }}"
  notify: restart es

- name: remove keystore
  shell: "{{ es_install_dir }}/bin/elasticsearch-keystore remove {{ item.key  }}"
  become_user: "{{ es_run_user }}"
  when: 
    - item.key in keystore_list.stdout
    - item.state is defined and item.state == 'absent'
  loop: "{{ es_keystores }}"
  notify: restart es
