- name: set nofile in /etc/security/limits.conf
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nofile
    value: '65535'

- name: set nproc in /etc/security/limits.conf
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nproc
    value: '65535'

- name: set nofile in /etc/security/limits.conf
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: memlock
    value: unlimited

- name: set vm.vm.swappiness in /etc/sysctl.conf
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present

- name: set vm.max_map_count in /etc/sysctl.conf
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
