- name: get keystore list
  shell: "{{ es_install_dir }}/bin/elasticsearch-keystore list"
  become_user: "{{ es_run_user }}"
  changed_when: false
  register: keystore_list
  tags: test

- name: add access_key
  shell: "echo '{{ item.access_key }}' | {{ es_install_dir }}/bin/elasticsearch-keystore add s3.client.{{ item.client }}.access_key --stdin --force"
  become_user: "{{ es_run_user }}"
  changed_when: true
  when: ("s3.client.{{ item.client }}.access_key | string not in keystore_list.stdout") 
  loop: "{{ es_repos }}"
  tags: test
